---
- hosts: raspi
  become: true
  tasks:
    - name: Make sure we can connect
      ping:
      #nginx
    - name: ensure nginx is latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
              name: nginx
              state: started
