---
- name: Add the ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php'
- name: Update cache
  apt:
        update_cache: yes 
        cache_valid_time: 3600
- name: Install PHP
  apt: name={{item}} state=present
  with_items:
        - php
        - php-fpm
        - php-mysql
        - php-xml

- name: Remove apache
  apt: name=apache2 state=absent
