- hosts: "*" 
  vars:
    backup_root: backup
  
  tasks:
  - name: config
    ios_facts:
      gather_subset: config

  - name: De output (configuratie) opslaan als een variabele
    ios_command:
      commands: show running  
    register: config          

  - name: Backup folder aanmaken
    file:
      path: "{{ backup_root }}"
      state: directory

  - name: Folder per device
    file:
      path: "{{ backup_root }}/{{ ansible_net_hostname }}"
      state: directory

  - name: Het tijdstip registreren
    command: date +%Y-%m-%d_%H:%M:%S
    register: timestamp

  - name: Bestanden kopiëren
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "{{ backup_root }}/{{ ansible_net_hostname }}/running-config_{{ timestamp.stdout }}"

 
