- name: Router configuratie 
  hosts: routers
  connection: network_cli
  
  tasks:
  - name: config file pushen
    ios_config:
      src: "./config.txt"

  - name: save running to startup
    ios_config:
      save_when: modified